"""empty message

Revision ID: da6d0a8a74ba
Revises: 4c587e6c44a3
Create Date: 2018-12-07 15:34:30.687843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6d0a8a74ba'
down_revision = '4c587e6c44a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cache',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_cache_username'), 'user_cache', ['username'], unique=True)
    op.create_table('image',
    sa.Column('ing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_cache.uid'], ),
    sa.PrimaryKeyConstraint('ing_id'),
    sa.UniqueConstraint('path'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_index(op.f('ix_user_cache_username'), table_name='user_cache')
    op.drop_table('user_cache')
    # ### end Alembic commands ###
